---
# Trusted homelab network
homelab_ipv4_network: "192.168.50.0/24"

# Host services
ssh_port: 22
external_ldap_port: 389
external_ldaps_port: 636
internal_ldap_port: 1389
internal_ldaps_port: 1636

# Podman service account
podman_user: app-runner
podman_subuid_start: 100000
podman_subuid_count: 65536
podman_subgid_start: 100000
podman_subgid_count: 65536

# Administration account
admin_user: elaverick

# SSH public key for the administration account
admin_authorized_key: >-
  ssh-ed25519
  AAAAC3NzaC1lZDI1NTE5AAAAIDIq2Y4iuLioCuGWdLqOCPtdDKMF8xUCAnnvPQ1q+7YU
  eddsa-key-20260807

# Domain configuration
domain: "laverick"
domain_suffix: "home.arpa"

# Certificate Server Host Port
intermediate_ca_host_port: 9000

# Certificates supplied by the offline Root CA
source_certs_path: "{{ playbook_dir }}/../certs"

root_certificate: "rootCA.crt"
intermediate_ca_certificate: "intermediateCA.crt"
intermediate_ca_private_key: "intermediateCA.key"

# LDAP Container configuration

ldap_container_name: "ldap-server"

ldap_ports:
  - "127.0.0.1:{{ internal_ldap_port }}:{{ external_ldap_port }}"
  - "127.0.0.1:{{ internal_ldaps_port }}:{{ external_ldaps_port }}"

ldap_domain: "{{ domain }}.{{ domain_suffix }}"
ldap_organisation: "Laverick Home Lab"

# LDAP connection

ldap_host: "127.0.0.1"

ldap_uri: "ldap://{{ ldap_host }}:{{ external_ldap_port }}"

# LDAP directory

domain_fqdn: "{{ domain }}.{{ domain_suffix }}"
ldap_base_dn: "{{ domain_fqdn.split('.') | map('regex_replace', '^(.*)$', 'dc=\\1') | join(',') }}"
ldap_admin_dn: "cn=admin,{{ ldap_base_dn }}"

# User/group configuration

uidNumber: 10000

ldapGroups:
  - name: users
    gidNumber: 10000

  - name: admins
    gidNumber: 10001

ldapUsers:
  - uid: elaverick
    firstname: Edward
    surname: Laverick
    gidNumber: 10000

  - uid: tlaverick
    firstname: Tom
    surname: Laverick
    gidNumber: 10000