---
# NGINX packages
nginx_packages:
  - nginx
  - libnginx-mod-stream

# NGINX configuration
nginx_config_path: /etc/nginx/nginx.conf

# NGINX stream configuration
nginx_stream_config_path: /etc/nginx/stream.conf.d

# NGINX HTTP configuration
nginx_http_config_path: /etc/nginx/conf.d

# ACME HTTP-01 challenge webroot
nginx_acme_webroot: "/var/lib/homelab/acme"
nginx_acme_challenge_path: "{{ nginx_acme_webroot }}/.well-known/acme-challenge"

nginx_acme_hostnames:
  - "pihole.{{ domain_fqdn }}"
  - "ca.{{ domain_fqdn }}"

# HTTP proxy definitions
nginx_http_proxies: []

# HTTPS/TLS passthrough proxies
nginx_https_proxies:
  - name: ca
    server_name: "ca.{{ domain_fqdn }}"
    backend_host: 127.0.0.1
    backend_port: "{{ intermediate_ca_host_port }}"

  - name: pihole
    server_name: "pihole.{{ domain_fqdn }}"
    backend_host: 127.0.0.1
    backend_port: 8443

# TCP proxy definitions
nginx_tcp_proxies:
  - name: ldap
    listen_port: "{{ external_ldap_port }}"
    backend_host: 127.0.0.1
    backend_port: "{{ internal_ldap_port }}"

  - name: ldaps
    listen_port: "{{ external_ldaps_port }}"
    backend_host: 127.0.0.1
    backend_port: "{{ internal_ldaps_port }}"

  - name: pihole-dns-tcp
    listen_port: 53
    backend_host: 127.0.0.1
    backend_port: 1053

# UDP proxy definitions
nginx_udp_proxies:
  - name: pihole-dns
    listen_port: 53
    backend_host: 127.0.0.1
    backend_port: 1053

# Ports exposed by NGINX through the host firewall
nginx_firewall_tcp_ports:
  - 53
  - 80
  - 443
  - "{{ external_ldap_port }}"
  - "{{ external_ldaps_port }}"

nginx_firewall_udp_ports:
  - 53