---

- name: Issue Pi-hole certificate
  ansible.builtin.include_role:
    name: certificate
  vars:
    certificate_name: "{{ pihole_container_name }}"
    certificate_deployment_target: "{{ pihole_container_name }}"
    certificate_deployment_mode: "bundle"
    certificate_deploy_path: "{{ pihole_tls_cert }}"
    certificate_restart_consumer_on_issue: true