---

- name: Pull Pi-hole container image
  become: true
  become_user: "{{ podman_user }}"
  containers.podman.podman_image:
    name: "{{ pihole_image }}"
    state: present

- name: Create Pi-hole data volume
  become: true
  become_user: "{{ podman_user }}"
  containers.podman.podman_volume:
    name: "{{ pihole_data_volume }}"
    state: present

- name: Configure Pi-hole TLS certificate
  ansible.builtin.import_tasks:
    file: certificate.yml

- name: Create Pi-hole web password secret
  become: true
  become_user: "{{ podman_user }}"
  containers.podman.podman_secret:
    name: "{{ pihole_web_password_secret_name }}"
    data: "{{ pihole_webserver_api_password }}"
    state: present
  no_log: true

- name: Create Pi-hole Quadlet
  become: true
  become_user: "{{ podman_user }}"
  containers.podman.podman_container:
    name: "{{ pihole_container_name }}"
    image: "{{ pihole_image }}"
    state: quadlet
    quadlet_filename: "{{ pihole_quadlet_filename }}"
    quadlet_file_mode: "0640"
    publish:
      - "{{ pihole_host_dns_port }}:53/tcp"
      - "{{ pihole_host_dns_port }}:53/udp"
      - "{{ pihole_host_https_port }}:443/tcp"
    env:
      TZ: "{{ pihole_timezone }}"
      FTLCONF_dns_listeningMode: "{{ pihole_dns_listening_mode }}"
      FTLCONF_dns_cnameRecords: "{{ pihole_dns_cname_records | join(';') }}"
      FTLCONF_webserver_domain: "{{ pihole_web_domain }}"
      FTLCONF_webserver_port: "443s"
      FTLCONF_webserver_tls_cert: "{{ pihole_tls_cert }}"
    secrets:
      - "{{ pihole_web_password_secret_name }},type=env,target=FTLCONF_webserver_api_password"
    volumes:
      - "{{ pihole_data_volume }}:/etc/pihole"
    quadlet_options:
      - "AutoUpdate=registry"
      - |
        [Install]
        WantedBy=default.target
  register: pihole_quadlet

- name: Reload app-runner user systemd manager
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
  when: pihole_quadlet.changed

- name: Enable and start Pi-hole container
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd_service:
    name: "{{ pihole_container_name }}.service"
    enabled: true
    state: "{{ 'restarted' if pihole_quadlet.changed else 'started' }}"
    scope: user

- name: Configure host DNS to use Pi-hole
  become: true
  ansible.builtin.lineinfile:
    path: /etc/dhcpcd.conf
    regexp: '^static domain_name_servers='
    line: 'static domain_name_servers=127.0.0.1'
    insertafter: EOF
  notify: Restart dhcpcd
