---
- name: Configure homelab base hosts
  hosts: physical_servers
  become: true
  gather_facts: true

  roles:
    - base_host
    - nginx
    - intermediate-ca
    - ldap
    - ldap-config
    - pihole
    - freeradius
    - software-inventory