---

- name: Create CA directory structure
  become: true
  become_user: "{{ podman_user }}"
  become_method: containers.podman.podman_unshare
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ intermediate_ca_uid }}"
    group: "{{ intermediate_ca_gid }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ intermediate_ca_volume_mountpoint }}/config"
      mode: "0755"

    - path: "{{ intermediate_ca_volume_mountpoint }}/certs"
      mode: "0755"

    - path: "{{ intermediate_ca_volume_mountpoint }}/secrets"
      mode: "0700"

    - path: "{{ intermediate_ca_volume_mountpoint }}/db"
      mode: "0700"

- name: Install Root CA certificate
  become: true
  become_user: "{{ podman_user }}"
  become_method: containers.podman.podman_unshare
  ansible.builtin.copy:
    src: "{{ intermediate_ca_source_certs_path }}/{{ intermediate_ca_root_certificate }}"
    dest: "{{ intermediate_ca_volume_mountpoint }}/certs/root_ca.crt"
    owner: "{{ intermediate_ca_uid }}"
    group: "{{ intermediate_ca_gid }}"
    mode: "0644"

- name: Install Intermediate CA certificate
  become: true
  become_user: "{{ podman_user }}"
  become_method: containers.podman.podman_unshare
  ansible.builtin.copy:
    src: "{{ intermediate_ca_source_certs_path }}/{{ intermediate_ca_certificate }}"
    dest: "{{ intermediate_ca_volume_mountpoint }}/certs/intermediate_ca.crt"
    owner: "{{ intermediate_ca_uid }}"
    group: "{{ intermediate_ca_gid }}"
    mode: "0644"

- name: Install encrypted Intermediate CA private key
  become: true
  become_user: "{{ podman_user }}"
  become_method: containers.podman.podman_unshare
  ansible.builtin.copy:
    src: "{{ intermediate_ca_source_certs_path }}/{{ intermediate_ca_private_key }}"
    dest: "{{ intermediate_ca_volume_mountpoint }}/secrets/intermediate_ca_key"
    owner: "{{ intermediate_ca_uid }}"
    group: "{{ intermediate_ca_gid }}"
    mode: "0600"