---

- name: Load Root CA secrets
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../ca/root/ansible/group_vars/vault.yaml"

- name: Create Intermediate CA private key password secret
  become: true
  become_user: "{{ podman_user }}"
  containers.podman.podman_secret:
    name: "intermediate_ca_password"
    state: present
    data: "{{ intermediateCA_key_passphrase }}"